# Outline

1. Ist dieses Buch für Dich geeignet?

1. Einführung
    + Hallo Welt
    + Was ist R?
    + Learning by doing
    + Was macht R besonders?
        + 'Sprache der Daten-Wissenschaft.'
        + 'R als Werkzeug.'
        + 'The R language is the scripting language for the R environment,
           just as VBA is the scripting language for Microsoft Excel.'
        + Vektoren statt Skalare.
    + Infrastruktur
        + Bibliotheken
        + Github
    + Geschichte
1. Los geht's
    + Hardware Anforderungen
    + Installation
        + R
        + R Studio
    + Programmausführung
        + R Shell
        + R Studio
        + Aufruf von der Kommandozeile
    + Hilfe
1. Syntax
    + Kommentare
    + Variablen
    + Zuweisungen
    + Blöcke und Einrückungen
    + Coding Guidelines
1. Datentypen
    + Vektoren
    + NA und NAN
    + Wahr und falsch
    + Text
    + Zahlen
    + Funktionen
1. Operatoren
1. Kontrollstrukturen
1. Komplexe Datentypen
    + Matrix
    + Data Frame
1. Kontext
    + Variablenkontext
    + Closures
    + Klassen und Objekte
1. Functionals
    + lapply()
    + sapply()
    + vapply()
    + map(), mapply()
    + mclapply(), mcMap()
1. Testing
    +
1. Bibliotheken
    + dplyr
    + ggplot2
    + knitr

